export enum ReturnOrderActionTypes {
  // Search
  RETURN_ORDER_SEARCH_REQ = '@RETURN_ORDER/SEARCH_REQ',
  RETURN_ORDER_SEARCH_SUCCESS = '@RETURN_ORDER/SEARCH_SUCCESS',
  RETURN_ORDER_SEARCH_FAIL = '@RETURN_ORDER/SEARCH_FAIL',

  // Create
  RETURN_ORDER_CREATE_REQ = '@RETURN_ORDER/CREATE_REQ',
  RETURN_ORDER_CREATE_SUCCESS = '@RETURN_ORDER/CREATE_SUCCESS',
  RETURN_ORDER_CREATE_FAIL = '@RETURN_ORDER/CREATE_FAIL',

  // Update SR
  RETURN_ORDER_UPDATE_SR_REQ = '@RETURN_ORDER/UPDATE_SR_REQ',
  RETURN_ORDER_UPDATE_SR_SUCCESS = '@RETURN_ORDER/UPDATE_SR_SUCCESS',
  RETURN_ORDER_UPDATE_SR_FAIL = '@RETURN_ORDER/UPDATE_SR_FAIL',

  // Update Status/Confirm
  RETURN_ORDER_UPDATE_STATUS_REQ = '@RETURN_ORDER/UPDATE_STATUS_REQ',
  RETURN_ORDER_UPDATE_STATUS_SUCCESS = '@RETURN_ORDER/UPDATE_STATUS_SUCCESS',
  RETURN_ORDER_UPDATE_STATUS_FAIL = '@RETURN_ORDER/UPDATE_STATUS_FAIL',

  // Cancel
  RETURN_ORDER_CANCEL_REQ = '@RETURN_ORDER/CANCEL_REQ',
  RETURN_ORDER_CANCEL_SUCCESS = '@RETURN_ORDER/CANCEL_SUCCESS',
  RETURN_ORDER_CANCEL_FAIL = '@RETURN_ORDER/CANCEL_FAIL',

  // Mark Edited
  RETURN_ORDER_MARK_EDITED_REQ = '@RETURN_ORDER/MARK_EDITED_REQ',
  RETURN_ORDER_MARK_EDITED_SUCCESS = '@RETURN_ORDER/MARK_EDITED_SUCCESS',
  RETURN_ORDER_MARK_EDITED_FAIL = '@RETURN_ORDER/MARK_EDITED_FAIL',

  // Reset
  RETURN_ORDER_RESET = '@RETURN_ORDER/RESET',

  // Set Step
  RETURN_ORDER_SET_STEP = '@RETURN_ORDER/SET_STEP',

  // New Sagas
  SEARCH_ORDER_REQUEST = '@RETURN_ORDER/SEARCH_ORDER_REQUEST',
  SEARCH_ORDER_SUCCESS = '@RETURN_ORDER/SEARCH_ORDER_SUCCESS',
  SEARCH_ORDER_FAILURE = '@RETURN_ORDER/SEARCH_ORDER_FAILURE',

  CREATE_RETURN_REQUEST = '@RETURN_ORDER/CREATE_RETURN_REQUEST',
  CREATE_RETURN_SUCCESS = '@RETURN_ORDER/CREATE_RETURN_SUCCESS',
  CREATE_RETURN_FAILURE = '@RETURN_ORDER/CREATE_RETURN_FAILURE',

  GENERATE_SR_REQUEST = '@RETURN_ORDER/GENERATE_SR_REQUEST',
  GENERATE_SR_SUCCESS = '@RETURN_ORDER/GENERATE_SR_SUCCESS',
  GENERATE_SR_FAILURE = '@RETURN_ORDER/GENERATE_SR_FAILURE',

  CONFIRM_RETURN_REQUEST = '@RETURN_ORDER/CONFIRM_RETURN_REQUEST',
  CONFIRM_RETURN_SUCCESS = '@RETURN_ORDER/CONFIRM_RETURN_SUCCESS',
  CONFIRM_RETURN_FAILURE = '@RETURN_ORDER/CONFIRM_RETURN_FAILURE',
  SET_STEP = "SET_STEP",
  RESET = "RESET",
}

export type ReturnOrderStep = 'search' | 'create' | 'sr' | 'preview' | 'confirm';

export interface SearchOrderRequest {
  searchTerm: string; // สำหรับรับค่า OrderNo หรือ SoNo
}

export interface OrderHeadDetail {
  orderNo: string;
  soNo: string;
  channelId: number;
  customerId: string;
  orderDate: string;
  salesStatus: string;
  mkpStatus: string;
  srNo: string | null;
}

export interface OrderLineDetail {
  orderNo: string;
  sku: string;
  itemName: string;
  qty: number;
  price: number;
  warehouseID: number;
}

export interface SearchOrderResponse {
  success: boolean;
  message?: string;
  data?: {
    head: OrderHeadDetail;
    lines: OrderLineDetail[];
  }
}
