// src/redux/orders/types/actions.ts

// Action Types
export enum OrderActionTypes {
    // Search Order
    SEARCH_ORDER_REQUEST = '@ORDER/SEARCH_ORDER_REQUEST',
    SEARCH_ORDER_SUCCESS = '@ORDER/SEARCH_ORDER_SUCCESS',
    SEARCH_ORDER_FAILURE = '@ORDER/SEARCH_ORDER_FAILURE',
    
    // Create Return Order
    CREATE_RETURN_ORDER_REQUEST = '@ORDER/CREATE_RETURN_ORDER_REQUEST',
    CREATE_RETURN_ORDER_SUCCESS = '@ORDER/CREATE_RETURN_ORDER_SUCCESS',
    CREATE_RETURN_ORDER_FAILURE = '@ORDER/CREATE_RETURN_ORDER_FAILURE',
    
    // Generate SR Number
    GENERATE_SR_REQUEST = '@ORDER/GENERATE_SR_REQUEST',
    GENERATE_SR_SUCCESS = '@ORDER/GENERATE_SR_SUCCESS',
    GENERATE_SR_FAILURE = '@ORDER/GENERATE_SR_FAILURE',
    
    // Update SR Number
    UPDATE_SR_REQUEST = '@ORDER/UPDATE_SR_REQUEST',
    UPDATE_SR_SUCCESS = '@ORDER/UPDATE_SR_SUCCESS',
    UPDATE_SR_FAILURE = '@ORDER/UPDATE_SR_FAILURE',
    
    // Update Order Status
    UPDATE_STATUS_REQUEST = '@ORDER/UPDATE_STATUS_REQUEST',
    UPDATE_STATUS_SUCCESS = '@ORDER/UPDATE_STATUS_SUCCESS',
    UPDATE_STATUS_FAILURE = '@ORDER/UPDATE_STATUS_FAILURE',
    
    // Cancel Order
    CANCEL_ORDER_REQUEST = '@ORDER/CANCEL_ORDER_REQUEST',
    CANCEL_ORDER_SUCCESS = '@ORDER/CANCEL_ORDER_SUCCESS',
    CANCEL_ORDER_FAILURE = '@ORDER/CANCEL_ORDER_FAILURE',
    
    // Mark Order as Edited
    MARK_EDITED_REQUEST = '@ORDER/MARK_EDITED_REQUEST',
    MARK_EDITED_SUCCESS = '@ORDER/MARK_EDITED_SUCCESS',
    MARK_EDITED_FAILURE = '@ORDER/MARK_EDITED_FAILURE',
    
    // Set Current Step
    SET_CURRENT_STEP = '@ORDER/SET_CURRENT_STEP',
    
    // Reset Order State
    RESET_ORDER = '@ORDER/RESET_ORDER',
    
    // Clear Error
    CLEAR_ERROR = '@ORDER/CLEAR_ERROR'
  }
  
  // Define steps in return order process
  export type OrderStep = 'search' | 'create' | 'sr' | 'preview' | 'confirm';