basePath: /api
definitions:
  api.Response:
    properties:
      message:
        type: string
      result: {}
      success:
        type: boolean
    type: object
  entity.District:
    properties:
      code:
        type: integer
      nameEN:
        type: string
      nameTH:
        type: string
      provinceCode:
        type: integer
    type: object
  entity.Order:
    properties:
      brandName:
        example: BEWELL
        type: string
      createDate:
        example: 20/11/2567
        type: string
      custAddress:
        example: 7/20 ซอย15/1
        type: string
      custDistrict:
        example: บางกรวย
        type: string
      custName:
        example: Num
        type: string
      custPhoneNum:
        example: "0921234567"
        type: string
      custPostCode:
        example: "11130"
        type: string
      custProvince:
        example: นนทบุรี
        type: string
      custSubDistrict:
        example: บางกรวย
        type: string
      orderLine:
        items:
          $ref: '#/definitions/entity.OrderLine'
        type: array
      orderNo:
        example: AB0001
        type: string
      updateDate:
        example: 20/11/2568
        type: string
      userCreated:
        example: intern
        type: string
      userUpdates:
        example: intern
        type: string
    type: object
  entity.OrderLine:
    properties:
      itemName:
        example: เก้าอี้
        type: string
      orderNo:
        example: AB0001
        type: string
      price:
        example: 199.05
        type: number
      qty:
        type: integer
      sku:
        type: string
    type: object
  entity.Province:
    properties:
      code:
        type: integer
      nameEN:
        type: string
      nameTH:
        type: string
    type: object
  entity.SubDistrict:
    properties:
      code:
        type: integer
      districtCode:
        type: integer
      nameEN:
        type: string
      nameTH:
        type: string
      zipCode:
        type: string
    type: object
  request.CreateOrderRequest:
    properties:
      brandName:
        example: BEWELL
        type: string
      custAddress:
        example: 7/20 ซอย15/1
        type: string
      custDistrict:
        example: บางกรวย
        type: string
      custName:
        example: Num
        type: string
      custPhoneNum:
        example: "0921234567"
        type: string
      custPostCode:
        example: "11130"
        type: string
      custProvince:
        example: นนทบุรี
        type: string
      custSubDistrict:
        example: บางกรวย
        type: string
      orderLines:
        items:
          $ref: '#/definitions/request.OrderLineRequest'
        type: array
      orderNo:
        example: AB0001
        type: string
    type: object
  request.LoginLark:
    properties:
      userID:
        example: DC99999
        type: string
      userName:
        example: eknarin
        type: string
    type: object
  request.LoginWeb:
    properties:
      password:
        example: asdfhdskjf
        type: string
      userName:
        example: eknarin
        type: string
    type: object
  request.OrderLineRequest:
    properties:
      itemName:
        example: เก้าอี้
        type: string
      orderNo:
        example: AB0001
        type: string
      price:
        example: 199.05
        type: number
      qty:
        type: integer
      sku:
        type: string
    type: object
  request.UpdateOrderRequest:
    properties:
      custAddress:
        example: 7/20 ซอย15/1
        type: string
      custDistrict:
        example: บางกรวย
        type: string
      custName:
        description: BrandName       *string `json:"brandName" db:"BrandName" example:"BEWELL"`
        example: Num
        type: string
      custPhoneNum:
        example: "0921234567"
        type: string
      custPostCode:
        example: "11130"
        type: string
      custProvince:
        example: นนทบุรี
        type: string
      custSubDistrict:
        example: บางกรวย
        type: string
      userUpdates:
        description: "CreateDate     \t*time.Time  `json:\"createDate\" db:\"CreateDate\"
          example:\"20/11/2567\"`\nUserCreated     *string \t`json:\"userCreated\"
          db:\"UserCreated\" example:\"intern\"`\nUpdateDate      *time.Time  `json:\"updateDate\"
          db:\"UpdateDate\" example:\"20/11/2568\"`"
        example: intern
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server for Boilerplate project .
  title: Boilerplate Service
  version: "1.0"
paths:
  /auth:
    get:
      consumes:
      - application/json
      description: A test endpoint to check if the user is authenticated and to demonstrate
        Swagger documentation.
      operationId: check-authentication
      produces:
      - application/json
      responses:
        "200":
          description: Authenticated user details
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                result:
                  additionalProperties: true
                  type: object
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Check Authentication
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Handles user login requests and generates a token for the authenticated
        user.
      operationId: user-login
      parameters:
      - description: User login credentials in JSON format
        in: body
        name: login-request
        required: true
        schema:
          $ref: '#/definitions/request.LoginWeb'
      produces:
      - application/json
      responses:
        "200":
          description: JWT token
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                result:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: User Login
      tags:
      - Auth
  /auth/login-lark:
    post:
      consumes:
      - application/json
      description: Handles user login requests and generates a token for the authenticated
        user.
      operationId: user-login-lark
      parameters:
      - description: User login from lark credentials from Lark in JSON format
        in: body
        name: Login-request-lark
        required: true
        schema:
          $ref: '#/definitions/request.LoginLark'
      produces:
      - application/json
      responses:
        "200":
          description: JWT token
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                result:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: User Lark Login
      tags:
      - Auth
  /auth/logout:
    post:
      description: Logs out the user by deleting the JWT token.
      operationId: user-logout
      responses:
        "200":
          description: Logout successful
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                result:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: User Logout
      tags:
      - Auth
  /constants/get-district:
    get:
      consumes:
      - application/json
      description: Get all Thai District.
      operationId: get-district
      produces:
      - application/json
      responses:
        "200":
          description: District
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                result:
                  items:
                    $ref: '#/definitions/entity.District'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: District not found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Get Thai District
      tags:
      - Constants
  /constants/get-province:
    get:
      consumes:
      - application/json
      description: Get all Thai Province.
      operationId: get-province
      produces:
      - application/json
      responses:
        "200":
          description: Province
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                result:
                  items:
                    $ref: '#/definitions/entity.Province'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Province not found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Get Thai Province
      tags:
      - Constants
  /constants/get-sub-district:
    get:
      consumes:
      - application/json
      description: Get all Thai SubDistrict.
      operationId: get-sub-district
      produces:
      - application/json
      responses:
        "200":
          description: SubDistrict
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                result:
                  items:
                    $ref: '#/definitions/entity.SubDistrict'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: SubDistrict not found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Get Thai SubDistrict
      tags:
      - Constants
  /orders/allgetorder:
    get:
      consumes:
      - application/json
      description: Get all Order
      operationId: Allget-order
      produces:
      - application/json
      responses:
        "200":
          description: Order Get
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                result:
                  items:
                    $ref: '#/definitions/entity.Order'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Province not found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Get Order
      tags:
      - Orders
  /orders/create-order:
    post:
      consumes:
      - application/json
      description: Create a new order
      operationId: create-order
      parameters:
      - description: Order Data
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/request.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Order Created
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                result:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Create Order
      tags:
      - Orders
  /orders/delete/{orderNo}:
    delete:
      consumes:
      - application/json
      description: Delete an order
      operationId: delete-order
      parameters:
      - description: Order Number
        in: path
        name: orderNo
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Order Deleted
          schema:
            $ref: '#/definitions/api.Response'
        "204":
          description: No Content, Order Delete Successfully
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Order Not Found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Delete Order
      tags:
      - Orders
  /orders/getbyID/{orderNo}:
    get:
      consumes:
      - application/json
      description: Get details of an order by its order number
      operationId: get-order-by-id
      parameters:
      - description: Order Number
        in: path
        name: orderNo
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Order Get by ID
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                result:
                  items:
                    $ref: '#/definitions/entity.Order'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Order not found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Get Order by ID
      tags:
      - Orders
  /orders/update/{orderNo}:
    put:
      consumes:
      - application/json
      description: Update an existing order
      operationId: update-order
      parameters:
      - description: Order Number
        in: path
        name: orderNo
        required: true
        type: string
      - description: Updated Order Data
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/request.UpdateOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Order Updated
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                result:
                  type: string
              type: object
        "204":
          description: No Content, Order Updated Successfully
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Order Not Found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Update Order
      tags:
      - Orders
swagger: "2.0"
